gameplay/urls.py
from django.conf.urls import url

from .views import game_detail, make_move, AllGamesList

urlpatterns = [
    url(r'detail/(?P<id>\d+)/$', game_detail, name="gameplay_detail"),
    url(r'make_move/(?P<id>\d+)/', make_move, name="gameplay_make_move"),
    url(r'all$', AllGamesList.as_view())
]

player/urls.py
from django.conf.urls import url
from django.contrib.auth.views import LoginView, LogoutView

from .views import home, new_invitation, accept_invitation, SignUpView,Contact

urlpatterns = [
    url(r'home$', home, name="player_home"),
    url(r'contact$', Contact, name="contact"),
    url(r'login$', LoginView.as_view(template_name="player/login_form.html"), name="player_login"),
    url(r'logout$', LogoutView.as_view(), name="player_logout"),
    url(r'new_invitation/$', new_invitation, name="player_new_invitation"),
    url(r'accept_invitation/(?P<id>\d+)/$', accept_invitation, name="player_accept_invitation"),
    url(r'signup$', SignUpView.as_view(), name='player_signup')
]

tictactoe/urls.py
from django.contrib import admin
from django.urls import include
from django.conf.urls import url

from .views import welcome

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^player/', include('player.urls')),
    url(r'^games/', include('gameplay.urls')),
    url(r'^$', welcome, name="tictactoe_welcome"),
    
]

gameplay/models.py
from __future__ import unicode_literals
from django.db import models
from django.db.models import Q
from django.contrib.auth.models import User
from django.urls import reverse
from django.core.validators import MinValueValidator, MaxValueValidator

GAME_STATUS_CHOICES = (
    ('F', 'First Player To Move'),
    ('S', 'Second Player To Move'),
    ('W', 'First Player Wins'),
    ('L', 'Second Player Wins'),
    ('D', 'Draw')
)

BOARD_SIZE = 3

class GamesQuerySet(models.QuerySet):
    def games_for_user(self, user):
        return self.filter(Q(first_player=user) | Q(second_player=user))
    
    def active(self):
        return self.filter(Q(status='F') | Q(status='S'))

class Game(models.Model):
    first_player = models.ForeignKey(User, related_name="game_first_player", on_delete=models.CASCADE)
    second_player = models.ForeignKey(User, related_name="game_second_player", on_delete=models.CASCADE)
    start_time = models.DateTimeField(auto_now_add=True)
    last_active = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=1, default='F', choices=GAME_STATUS_CHOICES)
    objects = GamesQuerySet.as_manager()

    def board(self):
        board = [[None for x in range(BOARD_SIZE)] for y in range(BOARD_SIZE)]
        for move in self.move_set.all():
            board[move.y][move.x] = move
        return board

    def is_users_move(self, user):
        return (user == self.first_player and self.status == 'F') or (user == self.second_player and self.status == 'S')

    def new_move(self):
        if self.status not in 'FS':
            raise ValueError("Cannot make move on finished game")
        return Move(
            game = self,
            by_first_player = self.status == 'F'
        )

    def update_after_move(self, move):
        self.status = self._get_game_status_after_move(move)

    def _get_game_status_after_move(self, move):
        x, y = move.x, move.y
        board = self.board()
        if (board[y][0] is not None and board[y][0]==board[y][1]==board[y][2]) or \
            (board[0][x] is not None and board[0][x]==board[1][x]==board[2][x]) or \
            (board[0][0] is not None and board[0][0]==board[1][1]==board[2][2]) or \
            (board[0][2] is not None and board[0][2]==board[1][1]==board[2][0]):
            return "W" if move.by_first_player else "L"
        if self.move_set.count()>=BOARD_SIZE**2:
            return "D"
        return 'S' if self.status == 'F' else 'F'

    def get_absolute_url(self):
        return reverse('gameplay_detail', args=[self.id])

    def __str__(self):
        return "{0} vs {1}".format(self.first_player, self.second_player)

class Move(models.Model):
    x = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(BOARD_SIZE-1)])
    y = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(BOARD_SIZE-1)])
    comment = models.CharField(max_length=300, blank=True)
    game = models.ForeignKey(Game, editable=False, on_delete=models.CASCADE)
    by_first_player = models.BooleanField(editable=False)

    def __eq__(self, other):
        if other is None:
            return False
        return other.by_first_player == self.by_first_player
    
    def save(self, *args, **kwargs):
        super(Move, self).save(*args, **kwargs)
        self.game.update_after_move(self)
        self.game.save()

gameplay/forms.py
from django.forms import ModelForm
from django.core.exceptions import ValidationError

from .models import Move

class MoveForm(ModelForm):
    class Meta:
        model = Move
        exclude = []

    def clean(self):
        x = self.cleaned_data.get("x")
        y = self.cleaned_data.get("y")
        game = self.instance.game
        try:
            if game.board()[y][x] is not None:
                raise ValidationError("Square is not empty")
        except IndexError:
            raise ValidationError("Invalid coordinates")
        return self.cleaned_data

gameplay/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.views.generic.list import ListView 

from .models import Game
from .forms import MoveForm

@login_required
def game_detail(request, id):
    game = get_object_or_404(Game, pk=id)
    context = {'game': game}
    if game.is_users_move(request.user):
        context['form'] = MoveForm()
    return render(request, "gameplay/game_detail.html", context)

@login_required
def make_move(request, id):
    game = get_object_or_404(Game, pk=id)
    if not game.is_users_move(request.user):
        raise PermissionDenied
    move = game.new_move()
    form = MoveForm(instance=move, data=request.POST)
    if form.is_valid():
        move.save()
        return redirect("gameplay_detail", id)
    else:
        return render(request, "gameplay/game_detail.html", {'game': game, 'form': form})

class AllGamesList(ListView):
    model = Game

templates/gameplay/game_detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
    {{game}}
{% endblock title %}

{% block styling %}
    {{block.super}}
    
{% endblock styling %}

{% block content %}
<style>
    .progress {
    height: 10px;
    border-radius: 10px;
    margin-bottom:1rem
}

.progress div {
    background-color: crimson
}
        {% comment %} .tictactoe-table {
            width: 430px;
            border-width: 2px;  border-radius:1rem
        }
       table> .tictactoe-cell {
            background-color: #debb27;
            width: 100px;
            height: 100px;
            text-align: center;
            vertical-align: middle !important;
            font-size: 60px;
        } {% endcomment %}
   

    </style>
    <div class="col-md-5">

        {% if game.status == 'F' %}
        <label class="label success" style="min-width:100%;background-color: #0088cc;padding: 0.5rem;color: white;text-align: center;margin-top:1rem;border-radius:0.5rem;margin-bottom:1rem">{{game.first_player}}'s Turn Now..</label>
            <div class="mt-2" id="inviteaccept">
                        <div class="progress" style="color:crimson">
                            <div class="progress-bar" role="progressbar" style="width: 50%" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100" style="color:crimson"></div>
                        </div>
            </div>
            
        {% elif game.status == 'S' %}
         <label class="label success" style="min-width:100%;background-color: #0088cc;padding: 0.5rem;color: white;text-align: center;margin-top:1rem;border-radius:0.5rem;margin-bottom:1rem"> {{game.second_player}}'s Turn Now..</label>
            <div class="mt-2" id="inviteaccept">
                        <div class="progress" style="color:crimson">
                            <div class="progress-bar" role="progressbar" style="width: 50%" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100" style="color:crimson"></div>
                        </div>
            </div>
           
        {% elif game.status == 'W' %}
         <label class="label success" style="min-width:100%;background-color: green;padding: 0.5rem;color: white;text-align: center;margin-top:1rem;border-radius:0.5rem;margin-bottom:1rem">{{game.first_player}} Has Won!</label>
            <div class="mt-2" id="inviteaccept">
                        <div class="progress" style="color:crimson">
                            <div class="progress-bar" role="progressbar" style="width: 50%" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100" style="color:crimson"></div>
                        </div>
            </div>
            
        {% elif game.status == 'L' %}
         <label class="label success" style="min-width:100%;background-color: green;padding: 0.5rem;color: white;text-align: center;margin-top:1rem;border-radius:0.5rem;margin-bottom:1rem"> {{game.second_player}} Has Won!</label>
            <div class="mt-2" id="inviteaccept">
                        <div class="progress" style="color:crimson">
                            <div class="progress-bar" role="progressbar" style="width: 50%" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100" style="color:crimson"></div>
                        </div>
            </div>
           
        {% elif game.status == 'D' %}
         <label class="label success" style="min-width:100%;background-color: green;padding: 0.5rem;color: white;text-align: center;margin-top:1rem;border-radius:0.5rem;margin-bottom:1rem">Cool, It's a draw!!</label>
            <div class="mt-2" id="inviteaccept">
                        <div class="progress" style="color:crimson">
                            <div class="progress-bar" role="progressbar" style="width: 50%" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100" style="color:crimson"></div>
                        </div>
            </div>
            
        {% endif %}

        <table class="table table-bordered tictactoe-table" style='  border-radius:1rem'>
            {% for row in game.board %}
                <tr>
                    {% for move in row %}
                        <td class="tictactoe-cell" style='border: 1px solid #4666FF;
  height: 100px;
  width: 100px;
  text-align: center;
  background: black;
  font-size: 60px; text-align: center;
            vertical-align: middle !important;
  color: #ff0070;
  box-shadow: 0 0 10px #4666FF, 0 0 10px #4666FF;
  text-shadow: 0 0 8px #ff0080, 0 0 10px #ff0080;
  cursor: pointer;
  border-radius:0.5rem'>
                            {% if move %}
                                {% if move.by_first_player %}
                                    X
                                {% else %}
                                    O
                                {% endif %}
                            {% endif %}
                        </td>
                    {% endfor %}
                </tr>
            {% endfor %}
        </table>
    </div>

    {% if form %}
        <div class="col-md-4">
                    <label class="label success" style="min-width:100%;background-color: crimson;padding: 0.5rem;color: white;text-align: center;margin-top:1rem;border-radius:0.5rem;margin-bottom:1rem">It's your Move</label>

            <form method="POST" action="{% url 'gameplay_make_move' game.id %}">
               <div id="div_id_x" class="form-group"> <label for="id_x" class="control-label  requiredField">
                Choose X Position<span class="asteriskField">*</span> </label> <div class="controls "> <input type="number" name="x" class="numberinput form-control" required id="id_x"> </div> </div> <div id="div_id_y" class="form-group"> <label for="id_y" class="control-label  requiredField">
                Choose Y Position<span class="asteriskField">*</span> </label> <div class="controls "> <input type="number" name="y" class="numberinput form-control" required id="id_y"> </div> </div> <div id="div_id_comment" class="form-group"> <label for="id_comment" class="control-label ">
                Your Comment
            </label> <div class="controls "> <input type="text" name="comment" maxlength="300" class="textinput textInput form-control" id="id_comment"> </div> </div>

        
                <button type="submit"  class='btn btn-primary'>Make Move</button>
               
                {% csrf_token %}
                
            </form>
        </div>
    {% endif %}
{% endblock content %}

templates/gameplay/game_list.html
{% extends "base.html"%}

{% block content %}
    <div class="well col-sm-6">
             <label class="label success" style="min-width:100%;background-color: #0088cc;padding: 0.5rem;color: white;text-align: center;margin-top:1rem;border-radius:0.5rem;margin-bottom:1rem">All Games : </label>

        {% include "player/game_list_snippet.html" with games_list=object_list %}
    </div>
{% endblock content %}